variable "project_id" { }
variable "region" { }
variable "zone" { }
variable "key" { }
variable "machine_type" { }
variable "cluster_count" { }
variable "cluster_name" { }
variable "ssd_name" { }
variable "compute_instance_environment" { }
variable "ubuntu_image" { }
