name: Build and Deploy

on:
  push:
    branches-ignore: main

env:
  PROJECT_ID: webids
  
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.WEBIDS_GCP_SA }}
        project_id: ${{ env.PROJECT_ID }}

    - run: |-
        gcloud services enable iam.googleapis.com
        gcloud iam service-accounts list


