  
name: Two
on:
  push:
    branches:
      - main
      - dev

env:
  PROJECT_ID: webids
  WEBIDS_GCP_SA: ${{ secrets.WEBIDS_GCP_SA }}
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  
jobs:
  setup-build-test:
    name: Setup, Build and Test
    runs-on: ubuntu-latest
    environment: development
    strategy:
      fail-fast: false
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.WEBIDS_GCP_SA }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: get commit message
        run: |
           echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})
           echo ${commitmsg}
