name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev
      - wip-gcp

env:
  PROJECT_ID: webids
  
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.WEBIDS_GCP_SA }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Setup GCP
      if: "! contains(toJSON(github.event.commits.*.msg), '[skip-ci]')"
      run: |
        chmod +x "${GITHUB_WORKSPACE}/.github/workflows/executors/init_gcp.sh"
        "${GITHUB_WORKSPACE}/.github/workflows/executors/init_gcp.sh"
    - name: Create Dev Box
      run: |
          echo ${service_account_key} > ${TF_VAR_key}
          chmod +x "${GITHUB_WORKSPACE}/.github/workflows/executors/gce.sh"
          "${GITHUB_WORKSPACE}/.github/workflows/executors/gce.sh"
